function Privacy() {
  return (
    <div className="text-justify text-balance">
      <div className="grid md:grid-cols-2 grid-cols-auto gap-4">
        <div className="mb-12">
          <h2 className="mb-4">Privacy Policy</h2>
          <div className="card bg-base-300 my-2 mb-12">
            <div className="card-body">
              <h6 className="mb-2">Last updated: February 16, 2025</h6>
              <p>
                This Privacy Policy describes Our policies and procedures on the
                collection, use and disclosure of Your information when You use
                the Service and tells You about Your privacy rights and how the
                law protects You. We use Your Personal data to provide and
                improve the Service. By using the Service, You agree to the
                collection and use of information in accordance with this
                Privacy Policy. This Privacy Policy has been created with the
                help of the Privacy Policy Generator.
              </p>
            </div>
          </div>
          <h2 className="mb-4">Interpretation and Definitions</h2>
          <div className="card bg-base-300 my-2">
            <div className="card-body">
              <h3 className="card-title">Interpretation</h3>
              <p>
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or in plural.
              </p>
            </div>
          </div>
          <div className="card bg-base-300 my-2">
            <div className="card-body">
              <h3 className="card-title">Definitions</h3>
              <p>For the purposes of this Privacy Policy:</p>
              <ul className="ul-default">
                <li>
                  <span className="font-bold">Account</span> means a unique
                  account created for You to access our Service or parts of our
                  Service.
                </li>
                <li>
                  <span className="font-bold">Affiliate</span> means an entity
                  that controls, is controlled by or is under common control
                  with a party, where "control" means ownership of 50% or more
                  of the shares, equity interest or other securities entitled to
                  vote for election of directors or other managing authority.
                </li>
                <li>
                  <span className="font-bold">Company</span> (referred to as
                  either "the Company", "We", "Us" or "Our" in this Agreement)
                  refers to Artify.
                </li>
                <li>
                  <span className="font-bold">Cookies</span> are small files
                  that are placed on Your computer, mobile device or any other
                  device by a website, containing the details of Your browsing
                  history on that website among its many uses.
                </li>
                <li>
                  <span className="font-bold">Country</span> refers to:
                  Philippines
                </li>
                <li>
                  <span className="font-bold">Device</span> means any device
                  that can access the Service such as a computer, a cellphone or
                  a digital tablet.
                </li>
                <li>
                  <span className="font-bold">Personal Data</span> is any
                  information that relates to an identified or identifiable
                  individual.
                </li>
                <li>
                  <span className="font-bold">Service</span> refers to the
                  Website.
                </li>
                <li>
                  <span className="font-bold">Service Provider</span> means any
                  natural or legal person who processes the data on behalf of
                  the Company. It refers to third-party companies or individuals
                  employed by the Company to facilitate the Service, to provide
                  the Service on behalf of the Company, to perform services
                  related to the Service or to assist the Company in analyzing
                  how the Service is used.
                </li>
                <li>
                  <span className="font-bold">
                    Third-party Social Media Service
                  </span>{" "}
                  refers to any website or any social network website through
                  which a User can log in or create an account to use the
                  Service.
                </li>
                <li>
                  <span className="font-bold">Usage Data</span> refers to data
                  collected automatically, either generated by the use of the
                  Service or from the Service infrastructure itself (for
                  example, the duration of a page visit).
                </li>
                <li>
                  <span className="font-bold">Website</span> refers to Artify,
                  accessible from{" "}
                  <a className="a-default" href="https://www.arti.fy">
                    https://www.arti.fy
                  </a>
                </li>
                <li>
                  <span className="font-bold">You</span> means the individual
                  accessing or using the Service, or the company, or other legal
                  entity on behalf of which such individual is accessing or
                  using the Service, as applicable.
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="mb-12">
          <h2 className="text-center mb-10 uppercase">
            Collecting and Using Your Personal Data
          </h2>
          <h2>Types of Data Collected</h2>
          <div className="card bg-base-300 my-2">
            <div className="card-body">
              <h3 className="card-title">Personal Data</h3>
              <p>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information may
                include, but is not limited to:
              </p>
              <ul className="ul-default">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>
            </div>
          </div>
          <div className="card bg-base-300 my-2">
            <div className="card-body">
              <h2>Usage Data</h2>
              <p className="!indent-0">
                Usage Data is collected automatically when using the Service.
              </p>
              <p>
                Usage Data may include information such as Your Device's
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that You visit, the
                time and date of Your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </p>
              <p>
                When You access the Service by or through a mobile device, We
                may collect certain information automatically, including, but
                not limited to, the type of mobile device You use, Your mobile
                device unique ID, the IP address of Your mobile device, Your
                mobile operating system, the type of mobile Internet browser You
                use, unique device identifiers and other diagnostic data.
              </p>
              <p>
                We may also collect information that Your browser sends whenever
                You visit our Service or when You access the Service by or
                through a mobile device.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Privacy;
